-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgnou2KjBIQmN49++y
bZpjw+zh0sft/kib4lmpMfMivMOhRANCAASanbKpQkZHwlV5y1jdMvtJsakR+y5Q
XnF1yubiKafxbjpNItgbT/w/WrG0GCnrSse/Kk3vtSwQeucP0DJFp9z4
-----END PRIVATE KEY-----