// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Gear AI - Chat with your vehicle!",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "Gear AI - Chat with your vehicle!",
            targets: ["AppModule"],
            bundleIdentifier: "com.gearai.app",
            teamIdentifier: "25QSUNYFC9",
            displayVersion: "0.1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .incomingNetworkConnections(),
                .outgoingNetworkConnections(),
                .camera(purposeString: "To add your vehicle instantly and accurately, Gear AI can use the camera to scan the Vehicle Identification Number (VIN) barcode on your car's door jamb or dashboard. This is the fastest way to create your car's digital twin."),
                .photoLibrary(purposeString: "To create a personalized garage, Gear AI needs access to your photo library. This allows you to select a profile picture and upload photos of your actual vehicles, making your digital garage truly your own."),
                .faceID(purposeString: "Enable Face ID to secure your digital garage. This adds a layer of biometric security, allowing you to quickly and safely access your vehicle data and authorize sensitive actions, such as managing your Web3 assets."),
                .userTracking(purposeString: "Allowing tracking helps us understand how you use Gear AI so we can improve our features and make the AI assistant smarter. Your data is used to enhance your experience and is not sold to third-party advertisers. You are in control of your data."),
                .locationWhenInUse(purposeString: "Gear AI uses your location while the app is open to provide location-aware features. This will enable you to find nearby mechanics and charging stations, track your drives for efficiency insights, and automatically log service locations."),
                .bluetoothAlways(purposeString: "To create a true digital twin of your car, Gear AI needs Bluetooth access. This allows the app to connect directly to On-Board Diagnostic (OBD2) scanners, enabling real-time health monitoring, live data streaming, and instant check engine light diagnosis."),
                .speechRecognition(purposeString: "Enable Speech Recognition to chat with your vehicle's AI assistant hands-free. This allows you to ask questions and issue commands using your voice, which is essential for safe operation while driving."),
                .microphone(purposeString: "Gear AI uses the microphone to enable voice commands for the chat assistant. Your voice is processed on-device and by Apple's servers to transcribe your questions, allowing for a seamless, hands-free experience."),
                .nearbyInteractionAllowOnce(purposeString: "Gear AI uses Nearby Interaction to enable secure, direct data sharing with trusted devices. This allows you to grant a mechanic temporary access to your vehicle's diagnostic data in person, without needing an internet connection, putting you in control of your data."),
                .localNetwork(purposeString: "Allowing local network access enables Gear AI to discover and communicate directly with hardware on your Wi-Fi network, such as OBD2 scanners or future smart vehicle accessories. This provides a faster and more reliable connection for real-time data.", bonjourServiceTypes: ["_gearai-diag._tcp", "_obd2-http._tcp", "_gearai-attest._udp"])
            ],
            appCategory: .productivity
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
